apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  annotations:
    triggers.tekton.dev/old-escape-quotes: "true"
  name: push-trigger-template
spec:
  params:
  - name: git-repository-url
    description: The git repository url
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineRun
    metadata:
      generateName: something-pushed-
      namespace: tekton
    spec:
      serviceAccountName: tekton-triggers-example-sa
      pipelineRef:
        name: tekton-demo-bipin
      workspaces:
      - name: pipeline-ws
        volumeClaimTemplate:
          spec:
            resources: 
              requests:
                storage: 100Mi
            accessModes:
              - ReadWriteOnce
        #emptyDir: {}
      resources:
        - name: git-repo
          resourceRef:
            name: git-repo
        - name: image-registry
          resourceRef:
            name: image-registry
